{
 "title": "Solar Panel",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Solar Panel Production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SolarPanel0\" or r[\"_measurement\"] == \"SolarPanel1\" or r[\"_measurement\"] == \"SolarPanel2\" or r[\"_measurement\"] == \"SolarPanel4\" or r[\"_measurement\"] == \"SolarPanel3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"production\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Panel Light",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SolarPanel0\" or r[\"_measurement\"] == \"SolarPanel1\" or r[\"_measurement\"] == \"SolarPanel2\" or r[\"_measurement\"] == \"SolarPanel4\" or r[\"_measurement\"] == \"SolarPanel3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"light\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Panel Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SolarPanel0\" or r[\"_measurement\"] == \"SolarPanel1\" or r[\"_measurement\"] == \"SolarPanel2\" or r[\"_measurement\"] == \"SolarPanel4\" or r[\"_measurement\"] == \"SolarPanel3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}