{
 "title": "Wind Turbine",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Wind Turbine Production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windTurbine0\" or r[\"_measurement\"] == \"windTurbine1\" or r[\"_measurement\"] == \"windTurbine2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"production\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wind Turbine Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windTurbine0\" or r[\"_measurement\"] == \"windTurbine1\" or r[\"_measurement\"] == \"windTurbine2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wind Turbine Vibration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windTurbine0\" or r[\"_measurement\"] == \"windTurbine1\" or r[\"_measurement\"] == \"windTurbine2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vibration\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}