version: "3.8"

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      network:
        ipv4_address: 172.20.0.100
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
